### PR TITLE
igvm_c: update makefile with DESTDIR and install dump_igvm

### PR DESCRIPTION
**Pull request by osteffenrh**
Some small improvements for the Makefile in igvm_c:
- Recognize the `DESTDIR` variable for staged installs
- Install the `dump_igvm` tool too

### CODE REVIEW

**Comment by chris-oo** [comment]
Thanks for your contribution! I updated the title a bit.

**Comment by chris-oo** [comment]
Are you looking for a new release for this change?

**Comment by osteffenrh** [comment]
Thanks for taking a look.

No rush with the release, not urgent.

**Comment by chris-oo** [comment]
No problem! I'll roll it into a future release at some point then.

**Pull request merged**
