### PR TITLE
Cargo.toml: Bump open-enum to latest version

### LINKED ISSUE #2: bump open-enum dep to 0.4.0
New version has nicer debug printing for enums.

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #2

### CODE REVIEW

**Comment by chris-oo** [comment]
Looks like a build issue? might need to tweak some derives maybe.

**Comment by jinankjain** [comment]
@chris-oo Looks like this commit which breaks things: https://github.com/kupiakos/open-enum/commit/ddd167a6335893d6b8361aa73a9d769838d68839

**Comment by jinankjain** [comment]
I have a fix for the aforementioned issue in this PR https://github.com/kupiakos/open-enum/pull/15

**Comment by chris-oo** [comment]
Okay, once the corresponding open_enum fix is in, we can take this.

**Comment by jinankjain** [comment]
> Okay, once the corresponding open_enum fix is in, we can take this.

The issue is fixed in 0.4.1. I have updated the PR to use the latest version.

**Comment by chris-oo** [comment]
Thanks! Set to automerge.

**Pull request merged**
